defaults:
  - pipeline: ???
  - dataset: ???

backtest:
  n_folds: 3
  n_jobs: 1
  metrics:
    - _target_: etna.metrics.MAE
    - _target_: etna.metrics.MSE
    - _target_: etna.metrics.MAPE
    - _target_: etna.metrics.SMAPE
    - _target_: etna.metrics.R2

dataset:
  exog: null

top: null
pattern_to_filter: 'etna/etna'
seed: 11