defaults:
  - pipeline: ???
  - dataset: ???

backtest:
  n_folds: 1
  n_jobs: 1
  metrics:
    - _target_: etna.metrics.MAE
    - _target_: etna.metrics.MSE
    - _target_: etna.metrics.MAPE
    - _target_: etna.metrics.SMAPE


seed: 11