from etna.analysis.feature_selection.mrmr_selection import AGGREGATION_FN
from etna.analysis.feature_selection.mrmr_selection import AggregationMode
from etna.analysis.feature_selection.mrmr_selection import mrmr
