---
name: Feature request
description: Suggest an idea for this project
labels: enhancement

body:
- type: textarea
  attributes:
    label: 🚀 Feature Request
    description: A clear and concise description of the feature proposal (description of what result should look like).
  validations:
    required: true

- type: textarea
  attributes:
    label: Motivation
    description: |
      Please outline the motivation for the proposal.
      Is your feature request related to a problem? e.g., I'm always frustrated when [...];
      Answers the question why it should be done.
      *If this is related to another GitHub issue, please link here too*
  validations:
    required: true

- type: textarea
  attributes:
    label: Proposal
    description: A clear and concise description of what you want to happen. Ideally step by step.
  validations:
    required: true

- type: textarea
  attributes:
    label: Test cases
    description: A description of test cases that should be added to test the feature.
  validations:
    required: false

- type: textarea
  attributes:
    label: Alternatives
    description: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: Added feature request 
        required: true
      - label: Added motivation
        required: true
      - label: Added proposal
        required: true
...
