---
name: "Typos and documentation fixes"
description: "Make documentation and tutorials even more awesome"
title: "[docs] "
labels: documentation

body:
- type: markdown
  attributes:
    value: |
      For typos and documentation fixes, please go ahead and:

      1. Create an issue. (You may leave it empty)
      2. Fix the typo.
      3. Submit a PR.

      Thank you!

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context or screenshots about the docs request here.
  validations:
    required: false