_target_: etna.pipeline.Pipeline
horizon: 14
model:
  _target_: etna.models.CatBoostModelMultiSegment
transforms:
- _target_: etna.transforms.TimeSeriesImputerTransform
  in_column: target
  strategy: mean
- _target_: etna.transforms.DensityOutliersTransform
  in_column: target
- _target_: etna.transforms.TimeSeriesImputerTransform
  in_column: target
  strategy: mean
- _target_: etna.transforms.AddConstTransform
  in_column: target
  value: 100
- _target_: etna.transforms.LogTransform
  in_column: target
- _target_: etna.transforms.BinsegTrendTransform
  in_column: target
  jump: 1
  min_size: 10
- _target_: etna.transforms.SegmentEncoderTransform
- _target_: etna.transforms.MinMaxScalerTransform
  in_column: target
  inplace: true
- _target_: etna.transforms.LagTransform
  in_column: target
  lags: ${shift:${pipeline.horizon},[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20]}
- _target_: etna.transforms.DateFlagsTransform
  day_number_in_month: true
  day_number_in_week: true
  is_weekend: true
  month_number_in_year: true
  week_number_in_month: true
  week_number_in_year: true
  year_number: true