backtest:
  n_folds: 3
  n_jobs: 1
  metrics:
  - _target_: etna.metrics.MAE
  - _target_: etna.metrics.MSE
  - _target_: etna.metrics.MAPE
  - _target_: etna.metrics.SMAPE
  - _target_: etna.metrics.R2
pipeline:
  _target_: etna.pipeline.Pipeline
  horizon: 10
  model:
    _target_: etna.models.CatBoostModelMultiSegment
    iterations: ${iterations}
    learning_rate: ${learning-rate}
  transforms:
  - _target_: etna.transforms.SegmentEncoderTransform
  - _target_: etna.transforms.LagTransform
    in_column: target
    lags: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
iterations: null
learning-rate: null