# fmt: off
DEFAULT = [
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.ProphetModel'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill', 'window': -1}, {'_target_': 'etna.transforms.MedianOutliersTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.HoltWintersModel', 'damped_trend': True, 'seasonal': 'add', 'trend': 'add'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill'}, {'_target_': 'etna.transforms.HolidayTransform', 'out_column': 'holiday_regressor'}, {'_target_': 'etna.transforms.SegmentEncoderTransform'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${mult:${horizon},3}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.BinsegTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${mult:${horizon},2}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${mult:${horizon},3}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.YeoJohnsonTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.ProphetModel', 'additional_seasonality_params': [{'fourier_order': 5, 'name': 'add_weekly', 'period': '${mult:${horizon}, 2}'}], 'seasonality_mode': 'multiplicative'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill', 'window': -1}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.ProphetModel', 'seasonality_mode': 'multiplicative'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill', 'window': -1}]} ,
    {'_target_': 'etna.ensembles.VotingEnsemble', 'pipelines': [{'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': 14, 'window': 1}, 'transforms': []}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': 7, 'window': 2}, 'transforms': []}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': 7, 'window': 7}, 'transforms': []}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${mult:${horizon},3}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.MedianOutliersTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.YeoJohnsonTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.ProphetModel'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill', 'window': -1}, {'_target_': 'etna.transforms.MedianOutliersTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.YeoJohnsonTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${mult:${horizon},3}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': '${horizon}', 'window': 3}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.HoltWintersModel', 'damped_trend': False, 'seasonal': 'add', 'trend': 'add'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill'}, {'_target_': 'etna.transforms.HolidayTransform', 'out_column': 'holiday_regressor'}, {'_target_': 'etna.transforms.SegmentEncoderTransform'}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.CatBoostMultiSegmentModel'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.BinsegTrendTransform', 'in_column': 'target', 'jump': 1, 'min_size': 10}, {'_target_': 'etna.transforms.SegmentEncoderTransform'}, {'_target_': 'etna.transforms.LagTransform', 'in_column': 'target', 'lags': '${shift:${horizon},[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]}'}, {'_target_': 'etna.transforms.DateFlagsTransform', 'day_number_in_month': True, 'day_number_in_week': True, 'is_weekend': True, 'month_number_in_year': True, 'week_number_in_month': True, 'week_number_in_year': True, 'year_number': True}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.ProphetModel', 'additional_seasonality_params': [{'fourier_order': 5, 'name': 'add_weekly', 'period': 15}, {'fourier_order': 5, 'name': 'add_monthly', 'period': 30}], 'seasonality_mode': 'multiplicative'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill', 'window': -1}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': '${horizon}', 'window': 3}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'forward_fill'}, {'_target_': 'etna.transforms.MedianOutliersTransform', 'in_column': 'target'}, {'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]} ,
    {'_target_': 'etna.ensembles.VotingEnsemble', 'pipelines': [{'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.NaiveModel', 'lag': 1}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.MovingAverageModel', 'window': '${pipelines[1].horizon}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': '${pipelines[2].horizon}', 'window': 4}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.SeasonalMovingAverageModel', 'seasonality': '${mult:${pipelines[3].horizon},4}', 'window': 3}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]}, {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.NaiveModel', 'lag': '${pipelines[4].horizon}'}, 'transforms': [{'_target_': 'etna.transforms.TimeSeriesImputerTransform', 'in_column': 'target', 'strategy': 'mean'}, {'_target_': 'etna.transforms.LinearTrendTransform', 'in_column': 'target'}]}]} ,
    {'_target_': 'etna.pipeline.Pipeline', 'horizon': '${__aux__.horizon}', 'model': {'_target_': 'etna.models.CatBoostMultiSegmentModel'}, 'transforms': [{'_target_': 'etna.transforms.StandardScalerTransform', 'in_column': 'target', 'with_std': False}, {'_target_': 'etna.transforms.LagTransform', 'in_column': 'target', 'lags': '${shift:${horizon},[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]}'}, {'_target_': 'etna.transforms.SegmentEncoderTransform'}, {'_target_': 'etna.transforms.DateFlagsTransform', 'day_number_in_week': True, 'is_weekend': True, 'week_number_in_year': True}, {'_target_': 'etna.transforms.SpecialDaysTransform'}]} ,
]
# fmt: on
