name: Test notebooks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  
  notebooks-test:
      if: github.event_name == 'push'||github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0 # TODO: remove after poetry fix
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install -E "all release jupyter" -vv
          poetry run pip install tsfresh==0.19.0
          poetry run pip install protobuf==3.20.1
      - name: Notebook runner
        run: |
          poetry run python -m scripts.notebook_runner
